spring:
  data:
    mongodb: 
      uri: mongodb://localhost:27017/myretaildb
  profiles: perf
  jmx:
    default-domain: MyRetailApp
       
myretail: 
  product: 
    productDetailsUrl: https://api.target.com/products/v3/
    fields: descriptions
    id_type: TCIN
    key: 43cJWpLjH8Z8oR18KdrZDBKAgLLQKJjz
    prdNotFoundCode: 410
    prdNotFoundMsg: Product Id is not found
    requestNotValidCode: 412
    requestNotValidMsg: Request is not valid
    genErrorCode: 500
    genErrorMsg: Service is unavailable now
    